site_name: Absorption Coefficient Calculator

nav:
    - Home: index.md
    - Models: models.md
    - TMM Calculator: absorptioncoeff.md
    - Side functions: utils.md


plugins:
    - mkdocstrings
    - search
    - bibtex:
        bib_file: "references.bib"
theme:
  name: material
  palette:
    primary: red
    accent: pink
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

markdown_extensions:
  - mdx_include:
      base_path: docs
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.superfences
  - tables
  - pymdownx.tabbed:
      alternate_style: true